-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 3
-- Total Raw Fields: 9
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Axes: Table: Axes. A distinct dimension, angle, or vector along which AI's impact on education can be examined -- e.g. 'Essay Writing vs. AI-Assisted Exploration'. New axes can be added freely as the project's scope grows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS axes (
  axis_id                             TEXT                 PRIMARY KEY          -- Stored identifier for the axis. Slug form, e.g. 'essay-vs-ai-conversation'.
);
ALTER TABLE axes ADD COLUMN IF NOT EXISTS title TEXT;                                               -- Short human-readable title of the axis, e.g. 'Essay Writing vs. AI-Assisted Exploration'.
ALTER TABLE axes ADD COLUMN IF NOT EXISTS summary TEXT;                                             -- One or two sentence summary of what this axis examines.
ALTER TABLE axes ADD COLUMN IF NOT EXISTS scenarios TEXT;                                           -- Example scenarios that illustrate this axis in practice.
ALTER TABLE axes ADD COLUMN IF NOT EXISTS considerations TEXT;                                      -- Individual pros and cons recorded against this axis.
COMMENT ON TABLE axes IS 'Table: Axes. A distinct dimension, angle, or vector along which AI''s impact on education can be examined -- e.g. ''Essay Writing vs. AI-Assisted Exploration''. New axes can be added freely as the project''s scope grows.';
COMMENT ON COLUMN axes.axis_id IS 'Stored identifier for the axis. Slug form, e.g. ''essay-vs-ai-conversation''.';
COMMENT ON COLUMN axes.title IS 'Short human-readable title of the axis, e.g. ''Essay Writing vs. AI-Assisted Exploration''.';
COMMENT ON COLUMN axes.summary IS 'One or two sentence summary of what this axis examines.';
COMMENT ON COLUMN axes.scenarios IS 'Example scenarios that illustrate this axis in practice.';
COMMENT ON COLUMN axes.considerations IS 'Individual pros and cons recorded against this axis.';

-- ----------------------------------------------------------------------------
-- Scenarios: Table: Scenarios. A concrete example that illustrates how an axis plays out in practice, such as a specific classroom assignment.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scenarios (
  scenario_id                         TEXT                 PRIMARY KEY          -- Stored identifier for the scenario. Slug form.
);
ALTER TABLE scenarios ADD COLUMN IF NOT EXISTS axis TEXT;                                           -- The axis this scenario illustrates.
ALTER TABLE scenarios ADD COLUMN IF NOT EXISTS title TEXT;                                          -- Short title of the scenario.
ALTER TABLE scenarios ADD COLUMN IF NOT EXISTS description TEXT;                                    -- Full description of how the scenario plays out.
COMMENT ON TABLE scenarios IS 'Table: Scenarios. A concrete example that illustrates how an axis plays out in practice, such as a specific classroom assignment.';
COMMENT ON COLUMN scenarios.scenario_id IS 'Stored identifier for the scenario. Slug form.';
COMMENT ON COLUMN scenarios.axis IS 'The axis this scenario illustrates.';
COMMENT ON COLUMN scenarios.title IS 'Short title of the scenario.';
COMMENT ON COLUMN scenarios.description IS 'Full description of how the scenario plays out.';

-- ----------------------------------------------------------------------------
-- Considerations: Table: Considerations. A single pro or con recorded against an axis.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS considerations (
  consideration_id                    TEXT                 PRIMARY KEY          -- Stored identifier for the consideration. Slug form.
);
ALTER TABLE considerations ADD COLUMN IF NOT EXISTS axis TEXT;                                      -- The axis this consideration belongs to.
ALTER TABLE considerations ADD COLUMN IF NOT EXISTS is_pro BOOLEAN;                                 -- TRUE if this consideration is a pro (benefit); FALSE if it is a con (drawback).
ALTER TABLE considerations ADD COLUMN IF NOT EXISTS statement TEXT;                                 -- The pro or con itself, stated in a sentence.
COMMENT ON TABLE considerations IS 'Table: Considerations. A single pro or con recorded against an axis.';
COMMENT ON COLUMN considerations.consideration_id IS 'Stored identifier for the consideration. Slug form.';
COMMENT ON COLUMN considerations.axis IS 'The axis this consideration belongs to.';
COMMENT ON COLUMN considerations.is_pro IS 'TRUE if this consideration is a pro (benefit); FALSE if it is a con (drawback).';
COMMENT ON COLUMN considerations.statement IS 'The pro or con itself, stated in a sentence.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Axes
CREATE INDEX IF NOT EXISTS idx_axes_scenarios ON axes (scenarios);
CREATE INDEX IF NOT EXISTS idx_axes_considerations ON axes (considerations);

-- Scenarios
CREATE INDEX IF NOT EXISTS idx_scenarios_axis ON scenarios (axis);

-- Considerations
CREATE INDEX IF NOT EXISTS idx_considerations_axis ON considerations (axis);

-- 4 FK index(es) declared.
