-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- get_scenarios_title
-- Helper function: Get Title from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_title(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_scenarios_description
-- Helper function: Get Description from Scenarios by ScenarioId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_scenarios_description(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM scenarios WHERE scenario_id = p_scenario_id);
$$ LANGUAGE sql STABLE;

-- get_considerations_is_pro
-- Helper function: Get IsPro from Considerations by ConsiderationId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_considerations_is_pro(p_consideration_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_pro FROM considerations WHERE consideration_id = p_consideration_id);
$$ LANGUAGE sql STABLE;

-- get_considerations_statement
-- Helper function: Get Statement from Considerations by ConsiderationId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_considerations_statement(p_consideration_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT statement FROM considerations WHERE consideration_id = p_consideration_id);
$$ LANGUAGE sql STABLE;

-- calc_axes_name
-- Field: Axes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_axes_name(p_axis_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(axis_id, '') FROM axes WHERE axis_id = p_axis_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_axes_count_of_considerations
-- Field: Axes.CountOfConsiderations
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_axes_count_of_considerations(p_axis_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM considerations WHERE axis = (SELECT NULLIF(axis_id, '') FROM axes WHERE axis_id = p_axis_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_axes_count_of_pros
-- Field: Axes.CountOfPros
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_axes_count_of_pros(p_axis_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM considerations WHERE axis = (SELECT NULLIF(axis_id, '') FROM axes WHERE axis_id = p_axis_id) AND is_pro = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_axes_count_of_cons
-- Field: Axes.CountOfCons
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_axes_count_of_cons(p_axis_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM considerations WHERE axis = (SELECT NULLIF(axis_id, '') FROM axes WHERE axis_id = p_axis_id) AND is_pro = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_scenarios_axis_title
-- Field: Scenarios.AxisTitle
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Title from related Axes


CREATE OR REPLACE FUNCTION calc_scenarios_axis_title(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title::text FROM axes WHERE axis_id = (SELECT axis FROM scenarios WHERE scenario_id = p_scenario_id));
$$ LANGUAGE sql STABLE;

-- get_axes_title
-- Helper function: Get Title from Axes by AxisId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_axes_title(p_axis_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM axes WHERE axis_id = p_axis_id);
$$ LANGUAGE sql STABLE;

-- get_axes_summary
-- Helper function: Get Summary from Axes by AxisId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_axes_summary(p_axis_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT summary FROM axes WHERE axis_id = p_axis_id);
$$ LANGUAGE sql STABLE;

-- calc_scenarios_name
-- Field: Scenarios.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_scenarios_name(p_scenario_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(scenario_id, '') FROM scenarios WHERE scenario_id = p_scenario_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_considerations_axis_title
-- Field: Considerations.AxisTitle
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Title from related Axes


CREATE OR REPLACE FUNCTION calc_considerations_axis_title(p_consideration_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title::text FROM axes WHERE axis_id = (SELECT axis FROM considerations WHERE consideration_id = p_consideration_id));
$$ LANGUAGE sql STABLE;

-- calc_considerations_name
-- Field: Considerations.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_considerations_name(p_consideration_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(consideration_id, '') FROM considerations WHERE consideration_id = p_consideration_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_considerations_kind
-- Field: Considerations.Kind
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_considerations_kind(p_consideration_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_pro FROM considerations WHERE consideration_id = p_consideration_id), FALSE) THEN ('Pro')::text ELSE ('Con')::text END)::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

