-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 3
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_considerations CASCADE;
DROP VIEW IF EXISTS vw_scenarios CASCADE;
DROP VIEW IF EXISTS vw_axes CASCADE;

-- ----------------------------------------------------------------------------
-- vw_axes: Table: Axes. A distinct dimension, angle, or vector along which AI's impact on education can be examined -- e.g. 'Essay Writing vs. AI-Assisted Exploration'. New axes can be added freely as the project's scope grows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_axes CASCADE;
CREATE VIEW vw_axes WITH (security_invoker = ON) AS
SELECT
  t.axis_id,                                                                    -- Stored identifier for the axis. Slug form, e.g. 'essay-vs-ai-conversation'.
  calc_axes_name(t.axis_id) AS name,                                            -- Display alias for the axis.
  t.title,                                                                      -- Short human-readable title of the axis, e.g. 'Essay Writing vs. AI-Assisted Exploration'.
  t.summary,                                                                    -- One or two sentence summary of what this axis examines.
  t.scenarios,                                                                  -- Example scenarios that illustrate this axis in practice.
  t.considerations,                                                             -- Individual pros and cons recorded against this axis.
  calc_axes_count_of_considerations(t.axis_id) AS count_of_considerations,      -- Total number of pros and cons recorded for this axis.
  calc_axes_count_of_pros(t.axis_id) AS count_of_pros,                          -- Number of pro considerations recorded for this axis.
  calc_axes_count_of_cons(t.axis_id) AS count_of_cons                           -- Number of con considerations recorded for this axis.
FROM axes t;

-- ----------------------------------------------------------------------------
-- vw_scenarios: Table: Scenarios. A concrete example that illustrates how an axis plays out in practice, such as a specific classroom assignment.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_scenarios CASCADE;
CREATE VIEW vw_scenarios WITH (security_invoker = ON) AS
SELECT
  t.scenario_id,                                                                -- Stored identifier for the scenario. Slug form.
  calc_scenarios_name(t.scenario_id) AS name,                                   -- Display alias for the scenario.
  t.axis,                                                                       -- The axis this scenario illustrates.
  calc_scenarios_axis_title(t.scenario_id) AS axis_title,                       -- Title of the parent axis.
  t.title,                                                                      -- Short title of the scenario.
  t.description                                                                 -- Full description of how the scenario plays out.
FROM scenarios t;

-- ----------------------------------------------------------------------------
-- vw_considerations: Table: Considerations. A single pro or con recorded against an axis.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_considerations CASCADE;
CREATE VIEW vw_considerations WITH (security_invoker = ON) AS
SELECT
  t.consideration_id,                                                           -- Stored identifier for the consideration. Slug form.
  calc_considerations_name(t.consideration_id) AS name,                         -- Display alias for the consideration.
  t.axis,                                                                       -- The axis this consideration belongs to.
  calc_considerations_axis_title(t.consideration_id) AS axis_title,             -- Title of the parent axis.
  t.is_pro,                                                                     -- TRUE if this consideration is a pro (benefit); FALSE if it is a con (drawback).
  t.statement,                                                                  -- The pro or con itself, stated in a sentence.
  calc_considerations_kind(t.consideration_id) AS kind                          -- Human-readable label for whether this is a pro or a con.
FROM considerations t;

