-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- PK strategy: string (FK values are rewritten to match each PK)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Axes: Table: Axes. A distinct dimension, angle, or vector along which AI's impact on education can be examined -- e.g. 'Essay Writing vs. AI-Assisted Exploration'. New axes can be added freely as the project's scope grows.
-- ----------------------------------------------------------------------------
INSERT INTO axes (axis_id, title, summary, scenarios, considerations)
VALUES ('essay-vs-ai-conversation', 'Essay Writing vs. AI-Assisted Exploration', 'Instead of assigning a written essay, the assignment becomes an exploratory conversation with an LLM, submitted as a shareable conversation link rather than a document.', NULL, NULL) ON CONFLICT (axis_id) DO UPDATE SET title = EXCLUDED.title, summary = EXCLUDED.summary, scenarios = EXCLUDED.scenarios, considerations = EXCLUDED.considerations;

-- ----------------------------------------------------------------------------
-- Scenarios: Table: Scenarios. A concrete example that illustrates how an axis plays out in practice, such as a specific classroom assignment.
-- ----------------------------------------------------------------------------
INSERT INTO scenarios (scenario_id, axis, title, description)
VALUES ('llm-conversation-assignment', 'essay-vs-ai-conversation', 'LLM Conversation as the Assignment', 'Rather than composing an essay about a subject, the student explores that same subject in conversation form with an LLM. The result submitted is a link to the conversation, not a document. The teacher can then ask the LLM about the conversation, or read the transcript directly.') ON CONFLICT (scenario_id) DO UPDATE SET axis = EXCLUDED.axis, title = EXCLUDED.title, description = EXCLUDED.description;

-- ----------------------------------------------------------------------------
-- Considerations: Table: Considerations. A single pro or con recorded against an axis.
-- ----------------------------------------------------------------------------
INSERT INTO considerations (consideration_id, axis, is_pro, statement)
VALUES ('authentic-exploration', 'essay-vs-ai-conversation', TRUE, 'A conversation format encourages genuine back-and-forth exploration of ideas rather than front-loading a fixed thesis.') ON CONFLICT (consideration_id) DO UPDATE SET axis = EXCLUDED.axis, is_pro = EXCLUDED.is_pro, statement = EXCLUDED.statement;

INSERT INTO considerations (consideration_id, axis, is_pro, statement)
VALUES ('loses-writing-practice', 'essay-vs-ai-conversation', FALSE, 'Students get less practice organizing their own thoughts into sustained, structured written prose.') ON CONFLICT (consideration_id) DO UPDATE SET axis = EXCLUDED.axis, is_pro = EXCLUDED.is_pro, statement = EXCLUDED.statement;

INSERT INTO considerations (consideration_id, axis, is_pro, statement)
VALUES ('teacher-can-audit-reasoning', 'essay-vs-ai-conversation', TRUE, 'The teacher can review the full conversation transcript, or ask the LLM directly about it, giving visibility into the student''s reasoning process that a finished essay doesn''t show.') ON CONFLICT (consideration_id) DO UPDATE SET axis = EXCLUDED.axis, is_pro = EXCLUDED.is_pro, statement = EXCLUDED.statement;

INSERT INTO considerations (consideration_id, axis, is_pro, statement)
VALUES ('conversation-quality-varies', 'essay-vs-ai-conversation', FALSE, 'The quality of what a student learns depends heavily on how well they prompt the LLM, which is an unevenly distributed skill.') ON CONFLICT (consideration_id) DO UPDATE SET axis = EXCLUDED.axis, is_pro = EXCLUDED.is_pro, statement = EXCLUDED.statement;

